### ISSUE TITLE
Cant install :\

### ISSUE THREAD

**Issue by RileyZack** [asunax-aaa/SynapseUI#10]
I get an error "failing to start the custom synapse ui. Can anyone help me install from scratch to insure that im installing correctly?

**Comment by asunax-aaa** [comment]
Normally you should get a error window that lets you expand the help information, this will tell you what the error is + how to fix it. Take a screenshot of the error and paste it here.

To install, simply drag and drop the ,exe into your already pre-existing Synapse X folder and open it.
Your Synapse folder should look something like this:
![image](https://user-images.githubusercontent.com/61892568/141694891-45502999-4617-4194-b3a8-cf97d062c1f7.png)

**Comment by RileyZack** [comment]
![image](https://user-images.githubusercontent.com/94223370/141698249-52d201a0-e0e1-4082-9f1f-3b5496f2b4dd.png)

Mine looks exactly like yours and yet it doesn't work... Ive also done everything it has told me to do on the possible fixes list.

**Comment by asunax-aaa** [comment]
Can you also take a screenshot of your Synapses bin folder? also hover over the SynapseUI.exe, you should see a file version.

Make sure you're using the latest version (1.0.14)
![image](https://user-images.githubusercontent.com/61892568/141698479-148f1f68-6adc-4274-88d4-cc0c2b895c4b.png)

**Comment by RileyZack** [comment]
![image](https://user-images.githubusercontent.com/94223370/141698537-68cf1f9b-addb-4901-842c-8ca4f0be0e5d.png)
Yes i am also using the correct version. 1.0.14.0

**Comment by asunax-aaa** [comment]
Seems like you're missing a ton of Syn X files, especially the sxlib folder which the UI relies on.

Synapse automatically downloads these when you run it, have you tried doing that? Running the official .exe and waiting for it to download its files, it may take a while if your internet is slow.

![image](https://user-images.githubusercontent.com/61892568/141698628-a4f17b28-91d2-41e4-8947-1e9df865f937.png)

**Comment by RileyZack** [comment]
I have ran it... Ill try to re-install it to see if that works.

**Comment by RileyZack** [comment]
Ive re-installed it, and now its working thanks :D
