### ISSUE TITLE
misspelling of dlls

### ISSUE THREAD

**Issue by raywave** [asunax-aaa/SynapseUI#8]
https://github.com/asunax-aaa/SynapseUI/blob/master/SynapseUI/Functions/EventMapping/EventMap.cs#L18
https://github.com/asunax-aaa/SynapseUI/blob/master/SynapseUI/Functions/EventMapping/EventMap.cs#L62

**Comment by asunax-aaa** [comment]
Thanks, I didn't notice that, nice catch.
